blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/david-t-martel/claude-code-integration/blob/main/docs/README.md
    about: Check our comprehensive documentation for setup guides, API reference, and troubleshooting.
  
  - name: 💬 Discussions
    url: https://github.com/david-t-martel/claude-code-integration/discussions
    about: Ask questions, share ideas, and discuss features with the community.
  
  - name: 🔒 Security Advisory
    url: https://github.com/david-t-martel/claude-code-integration/security/advisories/new
    about: Report sensitive security vulnerabilities privately through GitHub Security Advisories.
  
  - name: 📧 Email Support
    url: mailto:david.martel@auricleinc.com
    about: Contact the maintainer directly for complex issues or private discussions.